name: Publish Binaries

on:
  release:
    types:
      - published

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
          tar -czf ipfs-webui.tar.gz build/*

      - name: Copy build-artifacts to Release
        uses: skx/github-action-publish-binaries@release-0.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./ipfs-webui.tar.gz"
